spring:
  application:
    name: simple-mongo
  data:
    mongodb:
#      uri: mongodb://10.5.52.3:27017/test_stu
#      username: libin
#      password: libin
      host: 10.5.52.3
      port: 28018
      database: test_stu
debug: true
logging:
  level:
    com.jxedu: debug